var headerhtml = '';
headerhtml += '<!--登录-->';
headerhtml += '<div class="loginbox" id="login-widow">';
headerhtml += '   <div class="login_toptit">';
headerhtml += '     <div class="login_toptitname">账号登录</div>';
headerhtml += '      <div class="login_topclose"></div>';
headerhtml += '  </div>';
headerhtml += '  <div class="login_bot">';
headerhtml += '    <div class="login_botleft">';
headerhtml += '        <div class="one_login" style="display:block">';
headerhtml += '        <div class="logPword login_info"></div>';
headerhtml += '        <input type="text" id="username" name="username" maxlength="16" class="loginput" placeholder="用户名/手机">';
headerhtml += '       <input type="password" id="password" name="password" maxlength="20" class="loginput2" placeholder="密码">';
headerhtml += '       <div class="logPthree">';
headerhtml += '<input type="text" id="vcode" name="vcode" class="loginput3" maxlength="4" placeholder="验证码">';
headerhtml += '<img src="images/verify_code.ashx.png" id="vcodesj" class="log_yzm">';
headerhtml += '<span id="change_code">换一张</span>';
headerhtml += '</div>';
headerhtml += '</div>';
headerhtml += '<div class="perlog" id="lw-submit">登&nbsp;&nbsp;录</div>';
headerhtml += '    <div class="log_botpassword"><a href="" class="logpass" target="_blank">忘记密码？</a> <a href="" class="logreg" target="_blank">立即注册>></a></div>';
headerhtml += '   </div>';
headerhtml += '  <div class="login_botright">';
headerhtml += '      <p>可以使用以下方式登录</p>';
headerhtml += '      <p><a href=""><img src="../images/qq.png" class="logqq"></a><a href=""><img src="../images/wb.png" class="logwb"></a></p>';
headerhtml += '      <span><img src="../images/weixin.jpg"></span>';
headerhtml += '       <span>官方微信公众号</span>';
headerhtml += '   </div>';
headerhtml += '</div>';
headerhtml += '</div>';
headerhtml += '<div class="bg"></div>';
headerhtml += '<div class="top-bar" >';
headerhtml += '    <div class="commen-wrap h30">';
headerhtml += '        <p class="fl toplink">';
headerhtml += '            <span class="fl">唐山家教第一用户平台</span>';
headerhtml += '           <span class="top_line">|</span>';
headerhtml += '           <a id="smCode" href="javascript:;" class="wx_code">';
headerhtml += '               <img id="mxCode" src="../images/weixin.jpg" alt="微信">';
headerhtml += '           </a>';
headerhtml += '           <a href="" target="_blank" class="sina_link">访问新浪微博</a>';
//headerhtml+='           <span class="top_line">|</span>';
//headerhtml+='           <a href="javascript:;" class="app_link">87870APP</a>';
headerhtml += '           <span class="top_line">|</span>';
headerhtml += '           <a href="" target="_blank" class="top_link">云技术平台</a>';
headerhtml += '           <span class="top_line">|</span>';
headerhtml += '           <a href="" target="_blank" class="top_link">关于我们</a>';
headerhtml += '           <span class="top_line">|</span>';
headerhtml += '           <a href="" target="_blank" class="top_link">个人中心</a>';
headerhtml += '       </p>';
headerhtml += '       <label class="loginState">';
headerhtml += '           <a href="" class="reg fr">立即注册</a>';
headerhtml += '     	  <a href="javascript:;" id="login-pop" class="login fr">登录</a>';
// headerhtml += '     	  <a href="" target="_blank" class="gamejh fr">个人中心</a>';
headerhtml += '  	  </label>'
headerhtml += '   </div>';
headerhtml += '</div>';
headerhtml += '<div class="nav-wrap commen-wrap relative clearfix" >';
headerhtml += '    <a href="" class="fl logo">';
headerhtml += '        <img src="../images/logo.png" class="logo_img" alt="" />';
headerhtml += '    </a>';
headerhtml += '    <div class="nav-wrap-sub">';
headerhtml += '        <ul class="fl nav-list" id="nav-list">';
headerhtml += '            <li class="home">';
headerhtml += '                <a href="">';
headerhtml += '                    <span>首页</span><i>Home</i>';
headerhtml += '                </a>';
headerhtml += '            </li>';
headerhtml += '            <li>';
headerhtml += '                <a href="" >';
headerhtml += '                    <span>传统文化教育</span><i>Traditional culture</i>';
headerhtml += '                </a>';
headerhtml += '                <ul class="nav-sub-list nav-sub1">';
headerhtml += '                    <li>';
headerhtml += '                        <a href=""><i>&#x25aa;</i><span>国学知识</span></a>';
headerhtml += '                    </li>';
headerhtml += '                    <li>';
headerhtml += '                        <a href=""><i>&#x25aa;</i><span>国学教育</span></a>';
headerhtml += '                    </li>';
headerhtml += '                    <li>';
headerhtml += '                        <a href=""><i>&#x25aa;</i><span>名诗名词赏析</span></a>';
headerhtml += '                    </li>';
headerhtml+='                    <li>';
headerhtml += '                        <a href=""><i>&#x25aa;</i><span>节日教育</span></a>';
headerhtml+='                    </li>';
headerhtml += '                </ul>';
headerhtml += '            </li>';
headerhtml += '            <li>';
headerhtml += '                <a href="">';
headerhtml += '                    <span>现代家庭教育</span><i>Modern family</i>';
headerhtml += '                </a>';
headerhtml += '                <ul class="nav-sub-list nav-sub2" data-index="2">';
headerhtml += '                    <li>';
headerhtml += '                        <a href=""><i>&#x25aa;</i><span>智慧故事</span></a>';
headerhtml += '                    </li>';
headerhtml += '                    <li>';
headerhtml += '                        <a href=""><i>&#x25aa;</i><span>隔代教育</span></a>';
headerhtml += '                    </li>';
headerhtml += '                    <li>';
headerhtml += '                        <a href=""><i>&#x25aa;</i><span>赏析教育</span></a>';
headerhtml += '                    </li>';
headerhtml += '                    <li>';
headerhtml += '                        <a href=""><i>&#x25aa;</i><span>情商教育</span></a>';
headerhtml += '                    </li>';
headerhtml += '                    <li>';
headerhtml += '                        <a href=""><i>&#x25aa;</i><span>亲子沟通</span></a>';
headerhtml += '                    </li>';
headerhtml += '                    <li>';
headerhtml += '                        <a href=""><i>&#x25aa;</i><span>注意力培养</span></a>';
headerhtml += '                    </li>';
headerhtml += '                    <li>';
headerhtml += '                        <a href=""><i>&#x25aa;</i><span>家庭教育</span></a>';
headerhtml += '                    </li>';
headerhtml += '                </ul>';
headerhtml += '            </li>';
headerhtml += '            <li>';
headerhtml += '                <a href="">';
headerhtml += '                    <span>心理教育</span><i>Psychology</i>';
headerhtml += '                </a>';
headerhtml += '                <ul class="nav-sub-list nav-sub3" data-index="3" >';
headerhtml += '                    <li>';
headerhtml += '                        <a href=""><i>&#x25aa;</i><span>阶段心理</span></a>';
headerhtml += '                    </li>';
headerhtml += '                    <li>';
headerhtml += '                        <a href=""><i>&#x25aa;</i><span>走进心理学</span></a>';
headerhtml += '                    </li>';
headerhtml += '                    <li>';
headerhtml += '                        <a href=""><i>&#x25aa;</i><span>心理效应</span></a>';
headerhtml += '                    </li>';
headerhtml += '                    <li>';
headerhtml += '                        <a href=""><i>&#x25aa;</i><span>心理导航</span></a>';
headerhtml += '                    </li>';
headerhtml += '                    <li>';
headerhtml += '                        <a href=""><i>&#x25aa;</i><span>心理减压</span></a>';
headerhtml += '                    </li>';
headerhtml += '                    <li>';
headerhtml += '                        <a href=""><i>&#x25aa;</i><span>心理工作室</span></a>';
headerhtml += '                    </li>';
headerhtml += '                </ul>';
headerhtml += '            </li>';
headerhtml += '         <li>';
headerhtml += '             <a href="" target="_blank">';
headerhtml += '             <span >学习园地</span><i>Learning garden</i>';
headerhtml += '             </a>';
headerhtml += '                <ul class="nav-sub-list nav-sub4" data-index="4">';
headerhtml += '                    <li>';
headerhtml += '                        <a href=""><i>&#x25aa;</i><span>直播课程</span></a>';
headerhtml += '                    </li>';
headerhtml += '                    <li>';
headerhtml += '                        <a href=""><i>&#x25aa;</i><span>各校试题</span></a>';
headerhtml += '                    </li>';
headerhtml += '                    <li>';
headerhtml += '                        <a href=""><i>&#x25aa;</i><span>学习方法指导</span></a>';
headerhtml += '                    </li>';
headerhtml += '                    <li>';
headerhtml += '                        <a href=""><i>&#x25aa;</i><span>学习习惯养成</span></a>';
headerhtml += '                    </li>';
headerhtml += '                    <li>';
headerhtml += '                        <a href=""><i>&#x25aa;</i><span>右脑开发</span></a>';
headerhtml += '                    </li>';
headerhtml += '                </ul>';
headerhtml += '         </li>';
headerhtml += '            <li>';
headerhtml += '                <a href="">';
headerhtml += '                    <span>志愿者在线</span><i>Volunteer</i>';
headerhtml += '                </a>';
headerhtml += '            </li>';
headerhtml += '            <li>';
headerhtml += '                <a href="" target="_blank">';
headerhtml += '                    <span>名师在线</span><i>The teacher</i>';
headerhtml += '                </a>';
headerhtml += '            </li>';
headerhtml += '         <li>';
headerhtml += '             <a href="" target="_blank">';
headerhtml += '             <span >区县之窗</span><i>District and county</i>';
headerhtml += '             </a>';
headerhtml += '         </li>';
headerhtml += '        </ul>';
headerhtml += '        <a href="javascript:;" class="search fl">搜索</a>';
headerhtml += '    </div>';
headerhtml += '    <div class="search_wrap">';
headerhtml += '    <!-- 搜索 -->';
headerhtml += '            <input type="button" value="搜索" class="serarch_btn" name="serarch_btn" id="serarch_btn" />';
headerhtml += '            <a class="search_close" href="javascript:;">X</a>';
headerhtml += '        </div>';
headerhtml += '    <!-- 搜索 end-->';
headerhtml += '    </div>';
headerhtml += '</div>';
headerhtml += '<div class="nav-sub">';
headerhtml += '</div>';
if ($("#header").length > 0) {
    $("#header").html(headerhtml);
}
else {
    window.setTimeout(function () {
        $("#header").html(headerhtml);
    }, 1000);
}
